# Generated by Django 5.1.1 on 2024-10-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_text',
            field=models.TextField(default='shadik', max_length=300),
            preserve_default=False,
        ),
    ]
