# Generated by Django 5.1.1 on 2024-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_intro_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro_text',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
